#include <QObject>

#include "LangsAvailable.h"

const LangsCollection& langsAvailable()
{
    static const std::map<QString, QString> sLangsAvailable
    {
        { "af", QObject::tr("Afrikaans") },
        { "am", QObject::tr("Amharic") },
        { "ar", QObject::tr("Arabic") },        
        { "az", QObject::tr("Azerbaijani") },
        { "be", QObject::tr("Belarusian") },
        { "bg", QObject::tr("Bulgarian") },
        { "bn", QObject::tr("Bengali") },
        { "bs", QObject::tr("Bosnian") },
        { "ca", QObject::tr("Catalan") },
        { "ceb", QObject::tr("Cebuano") },
        { "co", QObject::tr("Corsican") },
        { "cs", QObject::tr("Czech") },
        { "cy", QObject::tr("Welsh") },
        { "da", QObject::tr("Danish") },
        { "de", QObject::tr("German") },
        { "el", QObject::tr("Greek") },
        { "en", QObject::tr("English") },
        { "eo", QObject::tr("Esperanto") },
        { "es", QObject::tr("Spanish") },
        { "et", QObject::tr("Estonian") },
        { "eu", QObject::tr("Basque") },
        { "fa", QObject::tr("Persian") },
        { "fi", QObject::tr("Finnish") },
        { "fr", QObject::tr("French") },
        { "fy", QObject::tr("Frisian") },
        { "ga", QObject::tr("Irish") },
        { "gd", QObject::tr("Scots Gaelic") },
        { "gl", QObject::tr("Galician") },
        { "gu", QObject::tr("Gujarati") },
        { "ha", QObject::tr("Hausa") },
        { "haw", QObject::tr("Hawaiian") },
        { "hi", QObject::tr("Hindi") },
        { "hmn", QObject::tr("Hmong") },
        { "hr", QObject::tr("Croatian") },
        { "ht", QObject::tr("Haitian Creole") },
        { "hu", QObject::tr("Hungarian") },
        { "hy", QObject::tr("Armenian") },
        { "id", QObject::tr("Indonesian") },
        { "ig", QObject::tr("Igbo") },
        { "is", QObject::tr("Icelandic") },
        { "it", QObject::tr("Italian") },
        { "iw", QObject::tr("Hebrew") },
        { "ja", QObject::tr("Japanese") },
        { "jw", QObject::tr("Javanese") },
        { "ka", QObject::tr("Georgian") },
        { "kk", QObject::tr("Kazakh") },
        { "km", QObject::tr("Khmer") },
        { "kn", QObject::tr("Kannada") },
        { "ko", QObject::tr("Korean") },
        { "ku", QObject::tr("Kurdish (Kurmanji)") },
        { "ky", QObject::tr("Kyrgyz") },
        { "la", QObject::tr("Latin") },
        { "lb", QObject::tr("Luxembourgish") },
        { "lo", QObject::tr("Lao") },
        { "lt", QObject::tr("Lithuanian") },
        { "lv", QObject::tr("Latvian") },
        { "mg", QObject::tr("Malagasy") },
        { "mi", QObject::tr("Maori") },
        { "mk", QObject::tr("Macedonian") },
        { "ml", QObject::tr("Malayalam") },
        { "mn", QObject::tr("Mongolian") },
        { "mr", QObject::tr("Marathi") },
        { "ms", QObject::tr("Malay") },
        { "mt", QObject::tr("Maltese") },
        { "my", QObject::tr("Myanmar (Burmese)") },
        { "ne", QObject::tr("Nepali") },
        { "nl", QObject::tr("Dutch") },
        { "no", QObject::tr("Norwegian") },
        { "ny", QObject::tr("Chichewa") },
        { "or", QObject::tr("Odia (Oriya)") },
        { "pa", QObject::tr("Punjabi") },
        { "pl", QObject::tr("Polish") },
        { "ps", QObject::tr("Pashto") },
        { "pt", QObject::tr("Portuguese") },
        { "ro", QObject::tr("Romanian") },
        { "ru", QObject::tr("Russian") },
        { "rw", QObject::tr("Kinyarwanda") },
        { "sd", QObject::tr("Sindhi") },
        { "si", QObject::tr("Sinhala") },
        { "sk", QObject::tr("Slovak") },
        { "sl", QObject::tr("Slovenian") },
        { "sm", QObject::tr("Samoan") },
        { "sn", QObject::tr("Shona") },
        { "so", QObject::tr("Somali") },
        { "sq", QObject::tr("Albanian") },
        { "sr", QObject::tr("Serbian") },
        { "st", QObject::tr("Sesotho") },
        { "su", QObject::tr("Sundanese") },
        { "sv", QObject::tr("Swedish") },
        { "sw", QObject::tr("Swahili") },
        { "ta", QObject::tr("Tamil") },
        { "te", QObject::tr("Telugu") },
        { "tg", QObject::tr("Tajik") },
        { "th", QObject::tr("Thai") },
        { "tk", QObject::tr("Turkmen") },
        { "tl", QObject::tr("Filipino") },
        { "tr", QObject::tr("Turkish") },
        { "tt", QObject::tr("Tatar") },
        { "ug", QObject::tr("Uyghur") },
        { "uk", QObject::tr("Ukrainian") },
        { "ur", QObject::tr("Urdu") },
        { "uz", QObject::tr("Uzbek") },
        { "vi", QObject::tr("Vietnamese") },
        { "xh", QObject::tr("Xhosa") },
        { "yi", QObject::tr("Yiddish") },
        { "yo", QObject::tr("Yoruba") },
        { "zh-CN", QObject::tr("Chinese") },
        { "zh-TW", QObject::tr("Chinese (Traditional)") },
        { "zu", QObject::tr("Zulu") },
    };

    return sLangsAvailable;
}
